# Generated by Django 6.0.1 on 2026-02-25 16:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('marketplace', models.CharField(max_length=50, verbose_name='Marketplace')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='disconnected', max_length=20, verbose_name='Status')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='Api Key')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Sync At')),
                ('sync_enabled', models.BooleanField(default=False, verbose_name='Sync Enabled')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Config')),
            ],
            options={
                'db_table': 'marketplace_connect_marketplaceconnection',
                'abstract': False,
            },
        ),
    ]
